domain: lit_pipes.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://lit_pipes.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /lit_pipes/      # place folder name if the site is served in a subfolder
title: Lit Pipes
description: 
# Use a remote theme hosted on GitHub (poole/hyde)
# See: https://github.com/poole/hyde
remote_theme: poole/hyde
markdown: kramdown
author: Lit Pipes
plugins:
  - jekyll-paginate
  - jekyll-remote-theme